# Generated by Django 4.1.2 on 2022-10-04 17:14

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
from django.core.validators import MaxValueValidator, MinValueValidator

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('name', models.CharField(max_length = 30,unique = True,blank = False,)),
                ('description',models.CharField(max_length = 120,)),
                ('quantity',models.IntegerField(validators = [MaxValueValidator(100),MinValueValidator(1)] )),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
